products = [
  {
    '_id': '1',
    'name': 'Oxidised earrings',
    'image': '/images/Oxi_ear.png',
    'description':
     ' The concept of beauty is naturally something we want to evoke, but to get vivid, sparkling text, we have to choose the most unique and apt wording possible.',
    'category': 'Jewellery',
    'price': 30,
    'countInStock': 10,
    'rating': 4.5,
    'numReviews': 12,
  },
  {
    '_id': '2',
    'name': 'Crystal earrings',
    'image': '/images/Cry_ear1.png',
    'description':
      'The concept of beauty is naturally something we want to evoke, but to get vivid, sparkling text, we have to choose the most unique and apt wording possible.',
    'category': 'Jewellery',
    'price': 30,
    'countInStock': 7,
    'rating': 4.0,
    'numReviews': 8,
  },
  {
    '_id': '3',
    'name': 'Crystal earrings',
    'image': '/images/Cry_ear2.png',
    'description':
      'The concept of beauty is naturally something we want to evoke, but to get vivid, sparkling text, we have to choose the most unique and apt wording possible.',
    'category': 'Jewellery',
    'price': 30,
    'countInStock': 5,
    'rating': 3,
    'numReviews': 12,
  },
  {
    '_id': '4',
    'name': 'Crystal earrings',
    'image': '/images/Cry_ear3.png',
    'description':
      'The concept of beauty is naturally something we want to evoke, but to get vivid, sparkling text, we have to choose the most unique and apt wording possible.',
    'category': 'Jewellery',
    'price': 30,
    'countInStock': 11,
    'rating': 5,
    'numReviews': 12,
  },
  {
    '_id': '5',
    'name': 'Hoop earrings',
    'image': '/images/Hoop_ear.png',
    'description':
      'The concept of beauty is naturally something we want to evoke, but to get vivid, sparkling text, we have to choose the most unique and apt wording possible.',
    'category': 'Jewellery',
    'price': 30,
    'countInStock': 7,
    'rating': 3.5,
    'numReviews': 10,
  },
  {
    '_id': '6',
    'name': 'Round studs',
    'image': '/images/Round_stu.jpg',
    'description':
      'The concept of beauty is naturally something we want to evoke, but to get vivid, sparkling text, we have to choose the most unique and apt wording possible.',
    'category': 'Jewellery',
    'price': 30,
    'countInStock': 10,
    'rating': 4,
    'numReviews': 12,
  },
  {
    '_id': '7',
    'name': 'Glitter hoop earrings',
    'image': '/images/gli_hoop_ear1.png',
    'description':
      'The concept of beauty is naturally something we want to evoke, but to get vivid, sparkling text, we have to choose the most unique and apt wording possible.',
    'category': 'Jewellery',
    'price': 25,
    'countInStock': 10,
    'rating': 4,
    'numReviews': 12,
  },
  {
    '_id': '8',
    'name': 'Glitter hoop earrings',
    'image': '/images/gli_hoop_ear2.png',
    'description':
      'The concept of beauty is naturally something we want to evoke, but to get vivid, sparkling text, we have to choose the most unique and apt wording possible.',
    'category': 'Jewellery',
    'price': 25,
    'countInStock': 10,
    'rating': 4,
    'numReviews': 12,
  },
  {
    '_id': '9',
    'name': 'Glitter hoop earrings',
    'image': '/images/gli_hoop_ear3.png',
    'description':
      'The concept of beauty is naturally something we want to evoke, but to get vivid, sparkling text, we have to choose the most unique and apt wording possible.',
    'category': 'Jewellery',
    'price': 25,
    'countInStock': 10,
    'rating': 4,
    'numReviews': 12,
  },
  {
    '_id': '10',
    'name': 'Glitter hoop earrings',
    'image': '/images/gli_hoop_ear4.png',
    'description':
      'The concept of beauty is naturally something we want to evoke, but to get vivid, sparkling text, we have to choose the most unique and apt wording possible.',
    'category': 'Jewellery',
    'price': 25,
    'countInStock': 10,
    'rating': 4,
    'numReviews': 12,
  },
  {
    '_id': '11',
    'name': 'Glitter hoop earrings',
    'image': '/images/gli_hoop_ear5.png',
    'description':
      'The concept of beauty is naturally something we want to evoke, but to get vivid, sparkling text, we have to choose the most unique and apt wording possible.',
    'category': 'Jewellery',
    'price': 25,
    'countInStock': 10,
    'rating': 4,
    'numReviews': 12,
  },
  {
    '_id': '12',
    'name': 'Glitter hoop earrings',
    'image': '/images/gli_hoop_ear6.png',
    'description':
      'The concept of beauty is naturally something we want to evoke, but to get vivid, sparkling text, we have to choose the most unique and apt wording possible.',
    'category': 'Jewellery',
    'price': 25,
    'countInStock': 10,
    'rating': 4,
    'numReviews': 12,
  },
  {
    '_id': '13',
    'name': 'Hoop earrings',
    'image': '/images/hoop_ear1.png',
    'description':
      'The concept of beauty is naturally something we want to evoke, but to get vivid, sparkling text, we have to choose the most unique and apt wording possible.',
    'category': 'Jewellery',
    'price': 30,
    'countInStock': 10,
    'rating': 4,
    'numReviews': 12,
  },
  {
    '_id': '14',
    'name': 'Hoop earrings',
    'image': '/images/hoop_ear2.png',
    'description':
      'The concept of beauty is naturally something we want to evoke, but to get vivid, sparkling text, we have to choose the most unique and apt wording possible.',
    'category': 'Jewellery',
    'price': 30,
    'countInStock': 10,
    'rating': 4,
    'numReviews': 12,
  },
  {
    '_id': '15',
    'name': 'Hoop earrings',
    'image': '/images/hoop_ear3.png',
    'description':
      'The concept of beauty is naturally something we want to evoke, but to get vivid, sparkling text, we have to choose the most unique and apt wording possible.',
    'category': 'Jewellery',
    'price': 30,
    'countInStock': 10,
    'rating': 4,
    'numReviews': 12,
  },
  {
    '_id': '16',
    'name': 'Hoop earrings',
    'image': '/images/hoop_ear4.png',
    'description':
      'The concept of beauty is naturally something we want to evoke, but to get vivid, sparkling text, we have to choose the most unique and apt wording possible.',
    'category': 'Jewellery',
    'price': 30,
    'countInStock': 10,
    'rating': 4,
    'numReviews': 12,
  },
  {
    '_id': '17',
    'name': 'Hoop earrings',
    'image': '/images/hoop_ear5.png',
    'description':
      'The concept of beauty is naturally something we want to evoke, but to get vivid, sparkling text, we have to choose the most unique and apt wording possible.',
    'category': 'Jewellery',
    'price': 30,
    'countInStock': 10,
    'rating': 4,
    'numReviews': 12,
  },
  {
    '_id': '18',
    'name': 'Hoop earrings',
    'image': '/images/hoop_ear6.png',
    'description':
      'The concept of beauty is naturally something we want to evoke, but to get vivid, sparkling text, we have to choose the most unique and apt wording possible.',
    'category': 'Jewellery',
    'price': 30,
    'countInStock': 10,
    'rating': 4,
    'numReviews': 12,
  },
  {
    '_id': '19',
    'name': 'Oxidised jhumkha',
    'image': '/images/Oxi_jhu1.jpg',
    'description':
     ' The concept of beauty is naturally something we want to evoke, but to get vivid, sparkling text, we have to choose the most unique and apt wording possible.',
    'category': 'Jewellery',
    'price': 50,
    'countInStock': 10,
    'rating': 4.5,
    'numReviews': 12,
  },
  {
    '_id': '20',
    'name': 'Oxidised jhumkha',
    'image': '/images/Oxi_jhu2.png',
    'description':
     ' The concept of beauty is naturally something we want to evoke, but to get vivid, sparkling text, we have to choose the most unique and apt wording possible.',
    'category': 'Jewellery',
    'price': 50,
    'countInStock': 10,
    'rating': 4.5,
    'numReviews': 12,
  },
  {
    '_id': '21',
    'name': 'Oxidised jhumkha',
    'image': '/images/Oxi_jhu2.png',
    'description':
     ' The concept of beauty is naturally something we want to evoke, but to get vivid, sparkling text, we have to choose the most unique and apt wording possible.',
    'category': 'Jewellery',
    'price': 50,
    'countInStock': 10,
    'rating': 4.5,
    'numReviews': 12,
  },
  {
    '_id': '22',
    'name': 'Oxidised earrings',
    'image': '/images/Oxi_ear1.png',
    'description':
     ' The concept of beauty is naturally something we want to evoke, but to get vivid, sparkling text, we have to choose the most unique and apt wording possible.',
    'category': 'Jewellery',
    'price': 80,
    'countInStock': 10,
    'rating': 4.5,
    'numReviews': 12,
  },
  {
    '_id': '23',
    'name': 'Oxidised earrings',
    'image': '/images/Oxi_ear2.png',
    'description':
     ' The concept of beauty is naturally something we want to evoke, but to get vivid, sparkling text, we have to choose the most unique and apt wording possible.',
    'category': 'Jewellery',
    'price': 80,
    'countInStock': 10,
    'rating': 4.5,
    'numReviews': 12,
  },
  {
    '_id': '24',
    'name': 'Oxidised earrings',
    'image': '/images/Oxi_ear3.png',
    'description':
     ' The concept of beauty is naturally something we want to evoke, but to get vivid, sparkling text, we have to choose the most unique and apt wording possible.',
    'category': 'Jewellery',
    'price': 80,
    'countInStock': 10,
    'rating': 4.5,
    'numReviews': 12,
  },
  {
    '_id': '25',
    'name': ' ',
    'image': '/images/wood_ear1.png',
    'description':
     ' The concept of beauty is naturally something we want to evoke, but to get vivid, sparkling text, we have to choose the most unique and apt wording possible.',
    'category': 'Jewellery',
    'price': 99,
    'countInStock': 10,
    'rating': 4.5,
    'numReviews': 12,
  },
  {
    '_id': '26',
    'name': 'Wooden earrings',
    'image': '/images/wood_ear2.png',
    'description':
     ' The concept of beauty is naturally something we want to evoke, but to get vivid, sparkling text, we have to choose the most unique and apt wording possible.',
    'category': 'Jewellery',
    'price': 99,
    'countInStock': 10,
    'rating': 4.5,
    'numReviews': 12,
  },
  {
    '_id': '27',
    'name': 'Wooden earrings',
    'image': '/images/wood_ear3.png',
    'description':
     ' The concept of beauty is naturally something we want to evoke, but to get vivid, sparkling text, we have to choose the most unique and apt wording possible.',
    'category': 'Jewellery',
    'price': 99,
    'countInStock': 10,
    'rating': 4.5,
    'numReviews': 12,
  },
  {
    '_id': '28',
    'name': 'Wooden earrings',
    'image': '/images/wood_ear4.png',
    'description':
     ' The concept of beauty is naturally something we want to evoke, but to get vivid, sparkling text, we have to choose the most unique and apt wording possible.',
    'category': 'Jewellery',
    'price': 99,
    'countInStock': 10,
    'rating': 4.5,
    'numReviews': 12,
  },
  {
    '_id': '29',
    'name': 'Wooden earrings',
    'image': '/images/wood_ear5.png',
    'description':
     ' The concept of beauty is naturally something we want to evoke, but to get vivid, sparkling text, we have to choose the most unique and apt wording possible.',
    'category': 'Jewellery',
    'price': 99,
    'countInStock': 10,
    'rating': 4.5,
    'numReviews': 12,
  },
  {
    '_id': '30',
    'name': 'Wooden earrings',
    'image': '/images/wood_ear6.png',
    'description':
     ' The concept of beauty is naturally something we want to evoke, but to get vivid, sparkling text, we have to choose the most unique and apt wording possible.',
    'category': 'Jewellery',
    'price': 99,
    'countInStock': 10,
    'rating': 4.5,
    'numReviews': 12,
  },
]



